# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#email: your-email@example.com
locale: "en-US"
title: "Commutating Cogitations"
description: "Homepage for Smit Chaudhary, Senior Physics Undergraduate, IIT Kanpur"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/img/cat.jpg"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax: true

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

#Search
search_full_content: true

#To link these to category and tags
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Build settings
markdown: kramdown
#theme: minima
#theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

paginate: 6
paginate_path: /page:num/

#Site Author
author:
  name: "Smit Chaudhary"
  picture: "/img/ProfilePic.jpeg"
  bio: "Senior Physics Undergraduate, IIT Kanpur"
  loaction: "Kanpur, India"
  email: smit@iitk.ac.in
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:smit@iitk.ac.in
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Smit_Chaudhary3"
    #- #label: "Facebook"
      #icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/smitchaudhary/"
    #- #label: "Instagram"
      #icon: "fab fa-fw fa-instagram"
      # url: "https://www.instagram.com/thesag66/"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://smitchaudhary.github.io"
    - label: "ResearchGate"
      icon: "fab fa-researchgate"
      url: "https://www.researchgate.net/profile/Smit_Chaudhary"
    - label: "Gmail"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:smitchaudhary10@gmail.com

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:smit@iitk.ac.in
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Smit_Chaudhary3"
    #- #label: "Facebook"
      #icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/smitchaudhary/"
    #- #label: "Instagram"
      #icon: "fab fa-fw fa-instagram"
      # url: "https://www.instagram.com/thesag66/"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://smitchaudhary.github.io"
    - label: "ResearchGate"
      icon: "fab fa-researchgate"
      url: "https://www.researchgate.net/profile/Smit_Chaudhary"
    - label: "Gmail"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:smitchaudhary10@gmail.com


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
